experiment_name: blackjack_ppo_ndnf_mt_al4_3e5

seed: 73
use_cuda: False
use_mps: False

use_decode_obs: True
model_latent_size: 4

use_eo: False
use_mt: True

log_interval: 100

plot_policy: True
target_policy_csv_path: ??? # to be filled in

aux_loss:
  dis_l1_mod_lambda: 1e-3
  tanh_conj_lambda: 0
  mt_ce2_lambda: 0.1


dds:
  initial_delta: 0.1
  delta_decay_delay: 50
  delta_decay_steps: 10
  delta_decay_rate: 1.1

total_timesteps: 3e5
learning_rate: 1e-2
num_envs: 8
num_steps: 64
anneal_lr: True
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 8
update_epochs: 4
norm_adv: True
clip_coef: 0.3
clip_vloss: True
ent_coef: 0.1
vf_coef: 1
max_grad_norm: 0.5
target_kl: null

# Video recording disabled for now
# video_recording: True
# video_recording_freq: 1000
# video_recording_env_seed: 123
