experiment_name: dc5_ppo_ndnf_mt_k2eoc4_tanh_exl8_3e5_aux_fixed_1

seed: 73
use_cuda: False
use_mps: False

log_interval: 100

customised_image_encoder:
  # Conv layer config:
  encoder_output_chanel: 4
  last_act: tanh
  kernel_size: 2
  # Extra layer config:
  use_extra_layer: True
  extra_layer_out: 8
  extra_layer_use_bias: True

use_eo: False
use_mt: True

aux_loss:
  emb_dis_lambda: 2e-9
  dis_l1_mod_lambda: 2e-5
  tanh_conj_lambda: 4e-7
  mt_ce2_lambda: 2e-5 # for NDNF-MT

dds:
  initial_delta: 0.1
  delta_decay_delay: 117
  delta_decay_steps: 7
  delta_decay_rate: 1.1

door_corridor:
  corridor_length: 5
  agent_view_size: 3
  max_steps: 270

total_timesteps: 3e5
learning_rate: 2e-3
num_envs: 8
num_steps: 32
anneal_lr: True
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 8
update_epochs: 16
norm_adv: True
clip_coef: 0.3
clip_vloss: True
ent_coef: 0.05
vf_coef: 0.82
max_grad_norm: 0.5
target_kl: null

# Video recording disabled for now
# video_recording: True
# video_recording_freq: 1000
# video_recording_env_seed: 123
