experiment_name: lc11_ppo_mlp_l4_1e5

seed: 73
use_cuda: False
use_mps: False

log_interval: 100

model_latent_size: 4
use_state_no_as_obs: True

total_timesteps: 1e5
learning_rate: 1e-2
num_envs: 8
num_steps: 64
anneal_lr: True
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 8
update_epochs: 4
norm_adv: True
clip_coef: 0.3
clip_vloss: True
ent_coef: 0.1
vf_coef: 1
max_grad_norm: 0.5
target_kl: null

# Long corridor configuration
long_corridor:
  corridor_length: 11
  start_state: 7
  goal_state: 3
  special_states: [5, 6, 7, 8]

# Video recording disabled for now
# video_recording: True
# video_recording_freq: 1000
# video_recording_env_seed: 123
